baseURL = 'https://mcbunkus.github.io/mcbunkus/'
languageCode = 'en-us'
title = 'mcbunkus'
theme = 'bunk'
summaryLength = 16

[pagination]
pagerSize = 5

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[params]
blogSection = "posts"
math = true


[[menus.main]]
name = "projects"
pageRef = '/projects'
weight = 10

[[menus.main]]
name = "posts"
pageRef = '/posts'
weight = 20
