baseURL = '/'
languageCode = 'en-us'
# theme = "terminal"
pagination.pagerSize = 5


[params]
contentTypeName = "posts"
showMenuItems = 2
centerTheme = true
math = true

[languages]
[languages.en]
languageName = "English"
title = "mcbunkus"

[languages.en.params]
subtitle = "A simple, retro theme for Hugo"
owner = "Austen LeBeau"
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "mcbunkus"
logoHomeLink = "/"

# [languages.en.menu]
# [[languages.en.menu.main]]
# identifier = "projects"
# name = "Projects"
# url = "/projects"


# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
noClasses = false

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[services]
[services.disqus]
shortname = 'mcbunkus'

[module]
# this is needed when you fetch the theme as a submodule to your repo.
# replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'
