baseURL = 'https://mcbunkus.github.io/mcbunkus/'
languageCode = 'en-us'
title = 'mcbunkus'
theme = 'bunk'
summaryLength = 16
paginate = 5

[params]
blogSection = "posts"

[[menus.main]]
name = "projects"
pageRef = '/projects'
weight = 10

[[menus.main]]
name = "posts"
pageRef = '/posts'
weight = 20
