baseURL = 'https://core-dumps.xyz/'
languageCode = 'en-us'
title = "core dumps"
summaryLength = 16
capitalizeListTitles = false
enableRobotsTXT = true

[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = 'mcbunkus'
